# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(choices=[(b'name', '\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e\u0431 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u0438 \u0438\u043c\u0435\u043d\u0438/\u0444\u0430\u043c\u0438\u043b\u0438\u0438'), (b'email', 'Email, \u043a\u043e\u0442\u043e\u0440\u044b\u0439 \u043d\u0435 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f, \u043d\u043e \u043d\u0430 \u043a\u043e\u0442\u043e\u0440\u044b\u0439 \u043c\u043e\u0436\u043d\u043e \u043d\u0430\u043f\u0438\u0441\u0430\u0442\u044c \u0447\u0435\u0440\u0435\u0437 \u0444\u043e\u0440\u043c\u0443'), (b'city', '\u0413\u043e\u0440\u043e\u0434'), (b'company', '\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f'), (b'link', '\u0421\u0441\u044b\u043b\u043a\u0430'), (b'extra_grade', '\u041a\u043b\u0430\u0441\u0441')], help_text=b'Name of field in student data', max_length=20)),
                ('field_value', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[(b'trusted', '\u0423\u0432\u0435\u0440\u0435\u043d\u043d\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435'), (b'untrusted', '\u041f\u043e\u0434 \u0441\u043e\u043c\u043d\u0435\u043d\u0438\u0435\u043c'), (b'suspicious', '\u041f\u043e\u0434\u043e\u0437\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0435'), (b'hidden', '\u0421\u043a\u0440\u044b\u0442\u043e\u0435')], default=b'trusted', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('graduation_year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('auth_code', models.CharField(blank=True, max_length=100)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_created', to='core.Student')),
                ('main_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Grade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.BooleanField(help_text=b'True is upvote, False is downvote')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.Student')),
                ('field_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.FieldValue')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set([('letter', 'graduation_year')]),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_activity', to='core.Student'),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='target',
            field=models.ForeignKey(help_text=b'Student to modify', on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='core.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('field_value', 'author')]),
        ),
    ]
