# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[(b'active', '\u0410\u043a\u0442\u0438\u0432\u043d\u044b\u0439'), (b'blocked', '\u0417\u0430\u0431\u043b\u043e\u043a\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439')], max_length=10)),
                ('owner_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='fieldvalue',
            name='author',
        ),
        migrations.RemoveField(
            model_name='student',
            name='auth_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='creator',
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='author_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_activity', to='core.AuthCode'),
        ),
        migrations.AddField(
            model_name='student',
            name='creator_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AuthCode'),
        ),
        migrations.AddField(
            model_name='vote',
            name='author_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.AuthCode'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('field_value', 'author_code')]),
        ),
    ]
