# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161223_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='author',
        ),
    ]
