# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_vote_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': '\u0433\u043e\u043b\u043e\u0441', 'verbose_name_plural': '\u0433\u043e\u043b\u043e\u0441\u0430'},
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='status_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f \u0441\u0442\u0430\u0442\u0443\u0441\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='author_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_activity', to='core.AuthCode', verbose_name='\u0410\u0432\u0442\u043e\u0440 \u043f\u0440\u0430\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='field_name',
            field=models.CharField(choices=[('name', '\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e\u0431 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u0438 \u0438\u043c\u0435\u043d\u0438/\u0444\u0430\u043c\u0438\u043b\u0438\u0438'), ('email', 'Email, \u043a\u043e\u0442\u043e\u0440\u044b\u0439 \u043d\u0435 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0435\u0442\u0441\u044f, \u043d\u043e \u043d\u0430 \u043a\u043e\u0442\u043e\u0440\u044b\u0439 \u043c\u043e\u0436\u043d\u043e \u043d\u0430\u043f\u0438\u0441\u0430\u0442\u044c \u0447\u0435\u0440\u0435\u0437 \u0444\u043e\u0440\u043c\u0443'), ('city', '\u0413\u043e\u0440\u043e\u0434'), ('company', '\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f/\u0412\u0423\u0417'), ('link', '\u0421\u0441\u044b\u043b\u043a\u0430'), ('social_fb', 'Facebook'), ('social_vk', '\u0412\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u0435'), ('grade', '\u041a\u043b\u0430\u0441\u0441')], max_length=20, verbose_name='\u0418\u043c\u044f \u043f\u043e\u043b\u044f'),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='field_value',
            field=models.CharField(max_length=200, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u043f\u043e\u043b\u044f'),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='status',
            field=models.CharField(choices=[('trusted', '\u0423\u0432\u0435\u0440\u0435\u043d\u043d\u0430\u044f'), ('untrusted', '\u041d\u0435\u0443\u0432\u0435\u0440\u0435\u043d\u043d\u0430\u044f'), ('hidden', '\u0421\u043a\u0440\u044b\u0442\u0430\u044f'), ('deleted', '\u0423\u0434\u0430\u043b\u0435\u043d\u043d\u0430\u044f')], default='trusted', max_length=20, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u043f\u0440\u0430\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='target',
            field=models.ForeignKey(help_text='\u0412\u044b\u043f\u0443\u0441\u043a\u043d\u0438\u043a', on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='core.Student'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='author_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.AuthCode', verbose_name='\u041a\u043e\u0434 \u0430\u0432\u0442\u043e\u0440\u0430 \u0433\u043e\u043b\u043e\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='field_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.FieldValue', verbose_name='\u041f\u043e\u043b\u0435'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.CharField(choices=[('added', '\u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u043e'), ('upvoted', '\u0437\u0430'), ('downvoted', '\u043f\u0440\u043e\u0442\u0438\u0432'), ('to_delete', '\u0443\u0434\u0430\u043b\u0438\u0442\u044c')], max_length=16, verbose_name='\u0422\u0438\u043f \u0433\u043e\u043b\u043e\u0441\u0430'),
        ),
    ]
