# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 01:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170114_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authcode',
            options={'verbose_name': '\u043a\u043e\u0434 \u0430\u0432\u0442\u043e\u0440\u0438\u0437\u0430\u0446\u0438\u0438', 'verbose_name_plural': '\u043a\u043e\u0434\u044b \u0430\u0432\u0442\u043e\u0440\u0438\u0437\u0430\u0446\u0438\u0438'},
        ),
        migrations.AlterModelOptions(
            name='fieldvalue',
            options={'verbose_name': '\u043f\u0440\u0430\u0432\u043a\u0430', 'verbose_name_plural': '\u043f\u0440\u0430\u0432\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': '\u043a\u043b\u0430\u0441\u0441', 'verbose_name_plural': '\u043a\u043b\u0430\u0441\u0441\u044b'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '\u0432\u044b\u043f\u0443\u0441\u043a\u043d\u0438\u043a', 'verbose_name_plural': '\u0432\u044b\u043f\u0443\u0441\u043a\u043d\u0438\u043a\u0438'},
        ),
        migrations.AddField(
            model_name='authcode',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u0437\u044b\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='authcode',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f \u0434\u0430\u043d\u043d\u044b\u0445'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authcode',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('\\w+')]),
        ),
        migrations.AlterField(
            model_name='authcode',
            name='status',
            field=models.CharField(choices=[('valid', '\u0432\u0430\u043b\u0438\u0434\u0435\u043d'), ('nonexistent', '\u043d\u0435\u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u044e\u0449\u0438\u0439'), ('revoked', '\u043e\u0442\u043e\u0437\u0432\u0430\u043d')], max_length=10),
        ),
    ]
