# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170207_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcode',
            name='cross_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
