# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_authcode_cross_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvalue',
            name='votes',
            field=models.FloatField(default=0),
        ),
    ]
