# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170209_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('torder', models.SmallIntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.Grade')),
            ],
            options={
                'ordering': ('torder',),
                'verbose_name': '\u0443\u0447\u0438\u0442\u0435\u043b\u044f',
                'verbose_name_plural': '\u0443\u0447\u0438\u0442\u0435\u043b\u044f',
            },
        ),
    ]
