# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='import_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
