# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_student_import_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='profile',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u0422\u0438\u043f \u043a\u043b\u0430\u0441\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(verbose_name='\u0413\u043e\u0434 \u0432\u044b\u043f\u0443\u0441\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='letter',
            field=models.CharField(max_length=1, verbose_name='\u0411\u0443\u043a\u0432\u0430 \u0432\u044b\u043f\u0443\u0441\u043a\u043d\u043e\u0433\u043e \u043a\u043b\u0430\u0441\u0441\u0430'),
        ),
    ]
