# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-23 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170211_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ('-timestamp',), 'verbose_name': '\u0433\u043e\u043b\u043e\u0441', 'verbose_name_plural': '\u0433\u043e\u043b\u043e\u0441\u0430'},
        ),
        migrations.AddField(
            model_name='authcode',
            name='id',
            field=models.IntegerField(default=0, verbose_name='ID'),
        ),
    ]
