# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-23 17:22
from __future__ import unicode_literals

from django.db import migrations


def fill_ids(apps, schema_editor):
    AuthCode = apps.get_model('core', 'AuthCode')
    for id, code in enumerate(AuthCode.objects.all()):
        code.id = id + 1
        code.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170923_1720'),
    ]

    operations = [
        migrations.RunPython(fill_ids)
    ]
