# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-23 17:39
from __future__ import unicode_literals

from django.db import migrations, models


def change_auth_code_fks(apps, schema_editor):
    AuthCode = apps.get_model('core', 'AuthCode')
    Student = apps.get_model('core', 'Student')
    FieldValue = apps.get_model('core', 'FieldValue')
    Vote = apps.get_model('core', 'Vote')

    code2id = {}
    for code in AuthCode.objects.all():
        code2id[code.code] = code.id

    for student in Student.objects.all():
        if student.creator_code_id:
            student.creator_code_id = code2id[student.creator_code_id]
            student.save()

    for obj in list(FieldValue.objects.all()) + list(Vote.objects.all()):
        if obj.author_code_id:
            obj.author_code_id = code2id[obj.author_code_id]
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0018_fill_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Student',
            name='creator_code',
            field=models.ForeignKey('AuthCode', blank=True, null=True, db_constraint=False)
        ),
        migrations.AlterField(
            model_name='FieldValue',
            name='author_code',
            field=models.ForeignKey('AuthCode', blank=True, null=True, db_constraint=False)
        ),
        migrations.AlterField(
            model_name='Vote',
            name='author_code',
            field=models.ForeignKey('AuthCode', blank=True, null=True, db_constraint=False)
        ),
        migrations.RunPython(change_auth_code_fks),
        migrations.AlterField(
            model_name='Student',
            name='creator_code',
            field=models.IntegerField('AuthCode', blank=True, null=True)
        ),
        migrations.AlterField(
            model_name='FieldValue',
            name='author_code',
            field=models.IntegerField('AuthCode', blank=True, null=True)
        ),
        migrations.AlterField(
            model_name='Vote',
            name='author_code',
            field=models.IntegerField('AuthCode', blank=True, null=True)
        ),
    ]
