# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-23 18:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0019_change_auth_code_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='code',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[^\\s]+$')]),
        ),
        migrations.RunSQL(
            ['ALTER TABLE core_authcode CHANGE id id INT (11) NOT NULL PRIMARY KEY AUTO_INCREMENT'],
            ['ALTER TABLE core_authcode CHANGE id id INT (11) NULL',
             'ALTER TABLE core_authcode DROP PRIMARY KEY'],
            state_operations=[migrations.AlterField(
                model_name='authcode',
                name='id',
                field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            )]
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='author_code',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    related_name='modify_activity',
                                    to='core.AuthCode',
                                    verbose_name='\u0410\u0432\u0442\u043e\u0440 \u043f\u0440\u0430\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='student',
            name='creator_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='core.AuthCode'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='author_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='votes', to='core.AuthCode',
                                    verbose_name='\u041a\u043e\u0434 \u0430\u0432\u0442\u043e\u0440\u0430 \u0433\u043e\u043b\u043e\u0441\u0430'),
        ),
    ]
